export default {
  headerLogoCvs: require('../../assets/images/logo_header_red.png'),
  loginLogoCvs: require('../../assets/images/logo_big_red.png'),
  icTrophy: require('../../assets/images/ic_trophy.png'),
  lenaLogin: require('../../assets/images/char_portrait_01.png'),
  lenaTip: require('../../assets/images/lena_advice.png'),
  arrowRightBrowse: require('../../assets/images/ic_arrow_right_browse.png'),
  arrowBack: require('../../assets/images/ic_nav_arrow_back.png'),
  arrowDropdown: require('../../assets/images/ic_arrow_dropdown.png'),
  arrowDropdownUp: require('../../assets/images/ic_arrow_dropdown_up.png'),
  icEye: require('../../assets/images/eye.png'),
  icEyeCrossed: require('../../assets/images/eye_crossed.png'),
  badgeBanana: require('../../assets/images/badge_banana.png'),
  plus: require('../../assets/images/plus.png'),
  tab_summary: require('../../assets/images/tab_summary.png'),
  tab_browse: require('../../assets/images/tab_browse.png'),
  tab_summary_selected: require('../../assets/images/tab_summary_selected.png'),
  tab_browse_selected: require('../../assets/images/tab_browse_selected.png'),
  icNavActivity: require('../../assets/images/ic_nav_activity.png'),
  icNavCarbs: require('../../assets/images/ic_nav_carbs.png'),
  icNavGlucose: require('../../assets/images/ic_nav_glucose.png'),
  icNavHeartRate: require('../../assets/images/ic_nav_heart_rate.png'),
  icNavMeds: require('../../assets/images/ic_nav_meds.png'),
  icNavWeight: require('../../assets/images/ic_nav_weight.png'),
  icCross: require('../../assets/images/ic_cross_close.png'),

  // Browse screen icons
  browseDataHistory: require('../../assets/images/browse_data_history.png'),
  browseDevices: require('../../assets/images/browse_devices.png'),
  browseFaq: require('../../assets/images/browse_faq.png'),
  browseGoals: require('../../assets/images/browse_goals.png'),
  browseLibrary: require('../../assets/images/browse_library.png'),
  browseLogout: require('../../assets/images/browse_logout.png'),
  browseProfile: require('../../assets/images/browse_profile.png'),
  browseRewards: require('../../assets/images/browse_rewards.png'),
  browseTips: require('../../assets/images/browse_tips.png'),
  browseActivity: require('../../assets/images/browseActivity.png'),

  // TODO: REPLACE LATER or DELETE
  hiGirl: require('../../assets/images/hiGirl.jpg'),
  pointGirl: require('../../assets/images/pointGirl.jpg'),
  thereGirl: require('../../assets/images/thereGirl.jpg'),
  arrow45: require('../../assets/images/arrow45.jpg'),
  finger: require('../../assets/images/finger.jpg'),
};
