// Auth
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SAVE_USERID = 'SAVE_USERID';
export const CREDENTIALS_SAVED = 'CREDENTIALS_SAVED';
export const CREDENTIALS_DELETED = 'CREDENTIALS_DELETED';
// TODO: remove after verification flow changes
export const SAVE_REGISTRATION_EMAIL = 'SAVE_REGISTRATION_EMAIL';
// TODO: remove after verification flow changes
export const DELETE_REGISTRATION_EMAIL = 'DELETE_REGISTRATION_EMAIL';

export const UPDATE_BIOMETRICS_AVAILABILITY = 'UPDATE_BIOMETRICS_AVAILABILITY';

export const UPDATE_USER_BLOCKED_STATUS = 'UPDATE_USER_BLOCKED_STATUS';
export const UPDATE_USER_LAST_ACTIVITY_DATE = 'UPDATE_USER_LAST_ACTIVITY_DATE';
export const UPDATE_TIMESECTION = 'UPDATE_TIMESECTION';
export const ON_START_SHOULD_BLOCK_CHECK_COMPLETED =
  'ON_START_SHOULD_BLOCK_CHECK_COMPLETED';
export const HIDE_GET_STARTED_FLOW = 'HIDE_GET_STARTED_FLOW';

// connectivity
export const UPDATE_CONNECTIVITY = 'UPDATE_CONNECTIVITY';
export const SET_BLE_MANAGER_STARTED = 'SET_BLE_MANAGER_STARTED';

export const ADD_NEW_ENTRY = 'ADD_NEW_ENTRY';
export const ADD_ENTRY_TO_THE_WHEEL = 'ADD_ENTRY_TO_THE_WHEEL';
export const ERASE_ENTRIES = 'ERASE_ENTRIES';
export const ADMIN_ERASE_ENTRIES = 'ADMIN_ERASE_ENTRIES';
export const CLEAN_NEW_ENTRY = 'CLEAN_NEW_ENTRY';
export const DELETE_ENTRY = 'DELETE_ENTRY';
export const FIRST_ENTRY_ADDED = 'FIRST_ENTRY_ADDED';
export const DETAILS_OPENED_FIRST_TIME = 'DETAILS_OPENED_FIRST_TIME';
export const PUSH_ENTRY_FIRST_TIME = 'PUSH_ENTRY_FIRST_TIME';

export const ADD_MAIN_NOTIFICATION = 'ADD_MAIN_NOTIFICATION';
export const ERASE_MAIN_NOTIFICATION = 'ERASE_MAIN_NOTIFICATION';
